[project]
name = "interlockingarea-rs"
version = "0.1.0"
description = "Python parts of Rust InterlockingArea implementation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "construct>=2.10.70",
    "jc>=1.25.5",
]
